version: "3"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  webapp:
    depends_on:
      - postgres
    environment:
      SERVER_URL: http://webapi:4426/api/v1
    image: portfolio-frontend

  webapi:
    image: portfolio-backend
    depends_on:
      - webapp
      - postgres
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:4426"
      ASPNETCORE_ENVIRONMENT: Development
      # ASPNETCORE_HTTPS_PORT: 5001
      # ASPNETCORE_Kestrel__Certificates__Default__Password: password
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - blob-data:/API/
      - data-protection:/root/.aspnet/DataProtection-Keys
      - ~/.aspnet/https:/https:ro

  nginx:
    image: nginx:latest
    depends_on:
      - webapi
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx

volumes:
  blob-data:
  data-protection:
  postgres-data:
